let token=localStorage.getItem('bromark_token');
const $=id=>document.getElementById(id);
function api(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:'Bearer '+token,'Content-Type':'application/json'};return fetch(path,opts).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j})}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');if(id==='dashboard')loadDashboard();if(id==='inventory')loadInventory()}
async function login(){try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const j=await r.json();if(!r.ok)throw Error(j.error);token=j.token;localStorage.setItem('bromark_token',token);start()}catch(e){$('loginMsg').textContent=e.message}}
function logout(){localStorage.removeItem('bromark_token');location.reload()}
function start(){if(!token)return;$('login').classList.add('hidden');$('main').classList.remove('hidden');show('dashboard')}
async function loadDashboard(){try{const d=await api('/api/dashboard');$('cards').innerHTML=[['Today Sales',d.sales],['Purchases',d.purchases],['Gross Profit',d.grossProfit],['Expenses',d.expenses],['Net Profit',d.netProfit]].map(x=>`<div class="metric">${x[0]}<b>₹${Number(x[1]||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</b></div>`).join('')}catch(e){if(e.message.includes('session'))logout()}}
async function loadInventory(){try{const ps=await api('/api/products');$('inventoryTable').innerHTML='<table><thead><tr><th>Product</th><th>Stock</th><th>Unit</th><th>Purchase</th><th>Sale</th><th>Min</th></tr></thead><tbody>'+ps.map(p=>`<tr><td>${p.name}</td><td>${p.openingStock}</td><td>${p.unit}</td><td>₹${p.purchasePrice}</td><td>₹${p.sellingPrice}</td><td>${p.minimumStock}</td></tr>`).join('')+'</tbody></table>'}catch(e){alert(e.message)}}
async function transaction(ev,type){ev.preventDefault();const b=Object.fromEntries(new FormData(ev.target));b.type=type;b.quantity=Number(b.quantity);b.rate=Number(b.rate);b.paid=Number(b.paid||0);try{const j=await api('/api/transactions',{method:'POST',body:JSON.stringify(b)});alert(`${type} saved: ${j.transactionId}`);ev.target.reset();show('dashboard')}catch(e){alert(e.message)}}
async function expense(ev){ev.preventDefault();const b=Object.fromEntries(new FormData(ev.target));b.amount=Number(b.amount);try{const j=await api('/api/expenses',{method:'POST',body:JSON.stringify(b)});alert('Expense saved: '+j.transactionId);ev.target.reset();show('dashboard')}catch(e){alert(e.message)}}
async function payment(ev){ev.preventDefault();const b=Object.fromEntries(new FormData(ev.target));b.amount=Number(b.amount);try{const j=await api('/api/payments',{method:'POST',body:JSON.stringify(b)});alert('Payment saved: '+j.transactionId);ev.target.reset();}catch(e){alert(e.message)}}
start();
